### ISSUE TITLE
Spaces in directory names incompatible with BSD make

### ISSUE THREAD

**Issue by adriaandegroot** [train-it-eu/remark-cmake#1]
(This is super-niche, and I realise this is your own documents repository) When there are spaces in directory names, CMake generates a Makefile that just-won't-work with BSD make; that's because BSD make is too dumb to handle spaces in any way (including \-escaping) in names. Using GNU make (with the regular Makefile) or Ninja (by switching CMake's generator) resolves the problem, but it'd be nice to have an example repository that "just works".

**Comment by mpusz** [comment]
Will do, thanks for pointing it out.

I should never put those spaces here and in my private slides repo, but as I did it already and resolved all the building issues, I forgot to make it right in the example repository.

**Comment by mpusz** [comment]
Fixed with 036a84f05cd01279e85ab65d80fc0b61bfce49f2
