### ISSUE TITLE
Use LANGUAGES NONE to speed up CMake step

### ISSUE THREAD

**Issue by adriaandegroot** [train-it-eu/remark-cmake#2]
Right now, `project()` in your examples doesn't specify languages, so CMake goes and looks for a C compiler and a C++ compiler. This is probably not necessary, and you can speed up the CMake step by adding `LANGUAGES NONE` to the `project()` call.

**Comment by mpusz** [comment]
Thanks for the suggestion. It can speed up the configure step a bit.

However, one of the use cases is to keep slides in parallel to the source code of samples used on slides and compile all at the same time with CMake and add_subdirectory() on both directories. In such a case C++ compiler is needed and disabling it may make people life harder. Especially if they are not CMake experts...
